// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3KqSHL2TP4n6BFETK3x_kzW6VJRW5ods',
    appId: '1:226745571394:web:bf08596070f5dca4d735db',
    messagingSenderId: '226745571394',
    projectId: 'tarea8-917ce',
    authDomain: 'tarea8-917ce.firebaseapp.com',
    storageBucket: 'tarea8-917ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjRbY7Ows4OMOEwgrnaCe2uDXlMsoOCVw',
    appId: '1:226745571394:android:d2b22de8e2dc1650d735db',
    messagingSenderId: '226745571394',
    projectId: 'tarea8-917ce',
    storageBucket: 'tarea8-917ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkyqzl9E2ToOfrwsAc_ObBJ8DRp_Tms_c',
    appId: '1:226745571394:ios:eb30cf582de7402bd735db',
    messagingSenderId: '226745571394',
    projectId: 'tarea8-917ce',
    storageBucket: 'tarea8-917ce.appspot.com',
    iosBundleId: 'com.example.tarea8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkyqzl9E2ToOfrwsAc_ObBJ8DRp_Tms_c',
    appId: '1:226745571394:ios:eb30cf582de7402bd735db',
    messagingSenderId: '226745571394',
    projectId: 'tarea8-917ce',
    storageBucket: 'tarea8-917ce.appspot.com',
    iosBundleId: 'com.example.tarea8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3KqSHL2TP4n6BFETK3x_kzW6VJRW5ods',
    appId: '1:226745571394:web:17069bbe61af8aefd735db',
    messagingSenderId: '226745571394',
    projectId: 'tarea8-917ce',
    authDomain: 'tarea8-917ce.firebaseapp.com',
    storageBucket: 'tarea8-917ce.appspot.com',
  );
}
